pg: &pg
  adapter: postgresql
  encoding: unicode
  pool: 5

default: &default
  <<: *pg

development:
  <<: *default
  host: localhost
  # username: postgres
  # password:
  database: todomvc_server_dev

test:
  <<: *default
  database: todomvc_server_test

personas:
  <<: *default
  database: todomvc_server_personas

production:
  <<: *default
  database: todomvc_server_prod
